name: Create Alfred Workflow

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.0.0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm i -P --ignore-scripts --frozen-lockfile --reporter=silent

      - name: Build Alfred Workflow
        id: alfred_builder
        uses: daolou/build-alfred-workflow2@v1.0.1
        with:
          workflow_dir: "."
          exclude_patterns: ".* *.cjs *.yaml docs/* CHANGELOG.md"

      - name: Rename
        run: mv ${{ steps.alfred_builder.outputs.workflow_file }} adcode.alfredworkflow

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Alfred Workflow
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: adcode.alfredworkflow
          asset_name: adcode.alfredworkflow
          asset_content_type: application/zip
