name: Create Alfred Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: alfred_builder
      name: Build Alfred Workflow
      uses: mperezi/build-alfred-workflow@v1
      with:
        workflow_dir: '.'
        exclude_patterns: '.git/* .github/* .gitignore .eslintignore .prettierignore'
    - id: create_release
      name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Alfred Workflow
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.alfred_builder.outputs.workflow_file }}
        asset_name: ${{ steps.alfred_builder.outputs.workflow_file }}
        asset_content_type: application/zip